name: Mutation testing

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - name: Run Stryker
        run: npx nx run metrics:stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  elements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - name: Run Stryker
        run: npx nx run elements:stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: mutation-coverage
          path: packages/elements/mutation-coverage.json

  metrics-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: npm ci
      - name: Run Stryker
        run: npx nx run metrics-scala:stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
